### ISSUE TITLE
TODO: DISTRICTS - Data Cleansing

### ISSUE THREAD

**Issue by itisaasta** [ashwindeo/dataschoolers#4]
Do any data cleansing necessary for the SCHOOL DISTRICTS dataset.

**Comment by ashwindeo** [comment]
Has anyone taken a look at this ? Else I can work start working on this from tomorrow. It might be good if someone is some EDA on this in its current shape in order to save time.

**Comment by ghost** [comment]
I'm working on it now, will update shortly.

**Comment by ashwindeo** [comment]
Awesome! If possible take a look at data_cleanup_school. Would be nice if we can have different data sources in sync as much as possible. Thanks.

**Comment by ghost** [comment]
I've updated the districts document and named it "districts_cleaned". I used the same field names as the school document where applicable and added additional field names. A couple notes:

-Districts are also called "agency" in the document.
-I removed about 1,700 duplicate/extra rows. There are now around 17,500 lines.
-Only about 11,000 districts have graduation data.
-I did not include the very detailed revenue data (Federal Rev. - Bilingual Education (B11) [District Finance] 2009-10) because it is not broken out very well (all revenue in "nonspecified" and it may not be relevant.
-Removed all missing data characters and replaced with blanks.

The "districts_cleaned" and "district_field_lookup" is on the file store folder.
